apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: emb-data
  name: emb-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2048Mi
status: {}
