apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: embedding
  name: embedding
spec:
  ports:
  - name: "7997"
    port: 7997
    targetPort: 7997
  selector:
    io.kompose.service: embedding
status:
  loadBalancer: {}
