apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: llamacpp
  name: llamacpp
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: llamacpp
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: llamacpp
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Paris
        image: llamacpp:rag
        name: llamacpp
        ports:
        - containerPort: 8888
        resources: {}
        tty: true
      restartPolicy: Always
status: {}
