apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mlflow-serveur
  name: mlflow-serveur
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: mlflow-serveur
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mlflow-serveur
    spec:
      containers:
      - env:
        - name: TZ
          value: '"Europe/Paris"'
        image: mlflow:v1
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 10
        name: mlflow-serveur
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
