apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ollama
  name: ollama
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ollama
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Paris
        image: ollama:v1
        livenessProbe:
          exec:
            command:
            - curl --fail http://localhost:11434/api/tags 2>/dev/null || exit 1
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 10
        name: ollama
        resources: {}
        tty: true
      restartPolicy: Never
status: {}
