apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mlflow-serveur
  name: mlflow-serveur
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mlflow-serveur
    spec:
      containers:
      - env:
        - name: TZ
          value: '"Europe/Paris"'
        image: mlflow:v1
        livenessProbe:
          exec:
            command:
            - curl --fail http://localhost:8080/ 2>/dev/null | grep MLflow || exit
              1
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 10
        name: mlflow-serveur
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Never
status: {}
